#!/usr/bin/env php
<?php

/*
 * This file is part of Ymir command-line tool.
 *
 * (c) Carl Alexander <support@ymirapp.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Ymir\Cli\Application;

require __DIR__.'/vendor/autoload.php';

$container = new ContainerBuilder();

// Load manual parameters
$container->setParameter('application_directory', __DIR__);
$container->setParameter('home_directory', rtrim(getenv('HOME'), '/'));
$container->setParameter('working_directory', rtrim(getcwd(), '/'));
$container->setParameter('ymir_api_url', getenv('YMIR_API_URL') ?: 'https://ymirapp.com/api');

// Load container configuration
$loader = new YamlFileLoader($container, new FileLocator());
$loader->load(__DIR__.'/config/services.yml');

// Compile container
$container->compile();

// Start the console application.
exit($container->get(Application::class)->run());
